### link base
GET http://localhost:3000/
### link pokemons sin filtrar
GET http://localhost:3000/pokemons
### query params
GET http://localhost:3000/pokemons?name=bulbasaur
### find a pokemon by name
GET http://localhost:3000/pokemons?name=Bulbasaur
### find pokemons by type
GET http://localhost:3000/pokemons?type=Planta

### upload a new pokemon
POST http://localhost:3000/pokemons
Content-Type: application/json

{
  "id": 143,
  "nombre": "Snorlax",
  "tipo": ["Normal"],
  "nivel": 38,
  "hp": 320
}

### update a pokemon
PUT http://localhost:3000/pokemons/update
Content-Type: application/json

{
  "id": 143,
  "nombre": "Snorlax",
  "tipo": ["Normal"],
  "nivel": 40,
  "hp": 350
}

### delete a pokemon by id
DELETE http://localhost:3000/pokemons?id=143